# Generated by Django 3.0.4 on 2020-03-17 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_recommendationsofparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationsofsitter',
            name='publish_data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
