# Generated by Django 3.0.4 on 2020-03-13 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.PositiveSmallIntegerField(default=1)),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/')),
                ('gender', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('specialization', models.TextField(blank=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=64, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=100)),
                ('driving_license', models.CharField(blank=True, max_length=100)),
                ('license_plate', models.CharField(blank=True, max_length=255)),
                ('delivery_method', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('lat', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.Profile')),
            ],
        ),
    ]
