# Generated by Django 3.0.4 on 2020-03-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200316_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_birthday',
            field=models.DateField(null=True),
        ),
    ]
