# Generated by Django 3.0.4 on 2020-03-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_birthday',
            field=models.DateField(blank=True),
        ),
    ]
