# Generated by Django 3.0.4 on 2020-03-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200316_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
