# Generated by Django 3.0.4 on 2020-03-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200316_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.TextField(blank=True, choices=[('Sitter', 'sitter'), ('parent', 'parent')], default=0),
        ),
    ]
