# Generated by Django 3.0.4 on 2020-03-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200316_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('SITTER', 'sitter'), ('PERANT', 'parent')], default='SITTER', max_length=32),
        ),
    ]
