# Generated by Django 3.0.4 on 2020-03-16 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_facebookfriend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookfriend',
            name='friend',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facebookfriend',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
