# Generated by Django 3.0.4 on 2020-03-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_socialtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialapp',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='socialtoken',
            name='account',
        ),
        migrations.RemoveField(
            model_name='socialtoken',
            name='app',
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
        migrations.DeleteModel(
            name='SocialApp',
        ),
        migrations.DeleteModel(
            name='SocialToken',
        ),
    ]
