# Generated by Django 3.0.4 on 2020-03-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('accounts', '0008_auto_20200321_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_token',
            field=models.ManyToManyField(to='authtoken.Token'),
        ),
    ]
