# Generated by Django 3.0.4 on 2020-03-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_birthday',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
