# Generated by Django 3.0.4 on 2020-03-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200322_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_birthday',
            new_name='birthday',
        ),
    ]
